# This configuration file specifies which hooks to run (ruff, prettier, and codespell), the versions of each tool, arguments to pass, and which files to include or exclude.
# It ensures that code is linted, formatted, and checked for spelling and quality issues automatically on every commit.
# To set up, run 'pre-commit install'. You can also run all hooks manually with 'pre-commit run --all-files'.

repos:
  # Ruff linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix] # To enable lint fixes
      # Run the formatter using configs in pyproject.toml
      - id: ruff-format

  # Prettier for formatting various file types
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: main # Use the latest version
    hooks:
      - id: prettier

  # Codespell for spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
