[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "remarx"
description = "Code for identifying Marx citations associated with the CDH project Citing Marx"
requires-python = ">=3.12"
readme = "README.md"
dynamic = ["version"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Text Processing",
]
dependencies = [
  "marimo>=0.13.11",
  "marimo[lsp]", # marimo language server protocol
  "ruff",
  "polars",
  "stanza",
  "orjsonl",
  "intspan",
  "lxml",
  "sentence-transformers",
  "chromadb",
  "transformers[torch]", # CPU-only version
  "tqdm",
  "scikit-learn",
  "scipy-stubs", # for mypy
]

[project.optional-dependencies]
dev = [
  "pre-commit",
  "remarx[test]",
]
test = [
  "pytest",
  "pytest-cov",
  # for scikit-learn type stubs for mypy
  "microsoft-python-type-stubs @ git+https://github.com/microsoft/python-type-stubs.git",
]

[project.scripts]
remarx-candidate-mentions = "remarx.candidate_mentions:main"
remarx-run-xslt = "remarx.run_xslt:main"

[tool.hatch.version]
path = "src/remarx/__init__.py"

[tool.ruff]
# Always generate Python 3.12-compatible code
target-version = "py312"

[tool.ruff.lint]
select = [
# ruff defaults
"E4",
"E7",
"E9",
"F",
# isort
"I",
]
# Can use to ignore specific rules within above selection
ignore = []

[tool.marimo.display]
cell_output = "below"
theme = "system"  # honor user preference, including in static html exports

[tool.marimo.runtime]
# Add project source directory to Python path
pythonpath = ["src"]

[tool.marimo.save]
format_on_save = true

[tool.marimo.diagnostics]
enabled = true

[tool.marimo.experimental]
lsp = true

[tool.hatch.metadata]
# so python type stubs can be installed from GitHub (i.e., direct reference)
allow-direct-references = true
