[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "remarx"
description = "Code for identifying Marx citations associated with the CDH project Citing Marx"
requires-python = ">=3.12"
readme = "README.md"
dynamic = ["version"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Text Processing",
]
dependencies = [
  "marimo",
  "marimo[lsp]", # marimo language server protocol
  "ruff",
  "nbconvert",
  "polars",
]

[project.optional-dependencies]
dev = [
  "pre-commit",
]

[tool.hatch.version]
path = "src/remarx/__init__.py"

[tool.ruff]
# Always generate Python 3.12-compatible code
target-version = "py312"

[tool.ruff.lint]
select = [
# ruff defaults
"E4",
"E7",
"E9",
"F",
# isort
"I",
]
# Can use to ignore specific rules within above selection
ignore = []

[tool.marimo.display]
cell_output = "below"

[tool.marimo.runtime]
# Add project source directory to Python path
pythonpath = ["src"]

[tool.marimo.save]
format_on_save = true

[tool.marimo.diagnostics]
enabled = true

[tool.marimo.experimental]
lsp = true
