name: Changelog Updated
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches: [develop, main]
jobs:
  check-changelog:
    name: Verify Changelog Updated
    runs-on: ubuntu-latest
    steps:
      - name: Check changelog
        uses: tarides/changelog-check-action@v3
        with:
          changelog: CHANGELOG.md
